# Generated by Django 3.2.8 on 2021-10-30 05:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.CharField(max_length=300)),
                ('serving_amount', models.CharField(choices=[(2, 2), (4, 4)], default=2, max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('prep_time', models.DurationField()),
                ('cooking_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=50)),
                ('allergens', models.ManyToManyField(blank=True, related_name='Allergens', to='menu_plan.Allergen')),
                ('ingredients', models.ManyToManyField(blank=True, to='menu_plan.Ingredients')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weeklymenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_date', models.DateField(default='2021-10-30')),
                ('week_number', models.IntegerField(default=0)),
                ('number_ofpeople', models.CharField(choices=[(2, 2), (4, 4)], default=2, max_length=50)),
                ('weelkly_recipe_amount', models.CharField(choices=[(3, 3), (4, 4), (5, 5)], default=4, max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
                ('recipes', models.ManyToManyField(blank=True, related_name='weeklyrecipes', to='menu_plan.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.ManyToManyField(blank=True, related_name='weeklyrecipes', to='menu_plan.Comments')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_plan.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='menu_plan.Tags'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='utensil',
            field=models.ManyToManyField(blank=True, related_name='Utensils', to='menu_plan.Utensil'),
        ),
        migrations.CreateModel(
            name='Nutritionalvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.IntegerField(blank=True, default=0)),
                ('fat', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=7)),
                ('of_which_saturates', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=7)),
                ('Carbohydrate', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=7)),
                ('of_which_sugars', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=7)),
                ('dietary_fibre', models.IntegerField(blank=True, default=0)),
                ('Protein', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=7)),
                ('Cholesterol', models.IntegerField(blank=True, default=0)),
                ('Sodium', models.IntegerField(blank=True, default=0)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu_plan.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('step', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=300)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_plan.recipe')),
            ],
        ),
    ]
